runtime: nodejs18
service: backend

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 20
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.75

env_variables:
  NODE_ENV: production
  JWT_SECRET: 6912jdu69
  GOOGLE_CLIENT_ID: 115639649689-n9740h8vm8cg40kqjtraean3kan7r6jh.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  FIREBASE_PROJECT_ID: test-69-424605
 

handlers:
  - url: /.*  
    script: auto

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
